Imported Upstream version 0.17.1

diff --git a/tests/twisted/run-test.sh.in b/tests/twisted/run-test.sh.in
--- a/tests/twisted/run-test.sh.in
+++ b/tests/twisted/run-test.sh.in
@@ -9,17 +9,35 @@ fi
 PYTHONPATH=@gabbletestsdir@/twisted
 export PYTHONPATH
 
+GABBLE_TWISTED_PATH=@gabbletestsdir@/twisted
+export GABBLE_TWISTED_PATH
+
 if [ -n "$1" ] ; then
   list="$1"
 else
   list=$(cat @gabbletestsdir@/twisted/gabble-twisted-tests.list)
 fi
 
-for i in $list ; do 
-  echo "Testing $i"
+any_failed=0
+for i in $list ; do
+  echo "Testing $i ..."
   sh @gabbletestsdir@/twisted/tools/with-session-bus.sh \
     --config-file=@gabbletestsdir@/twisted/tools/servicedir/tmp-session-bus.conf \
     -- \
     @PYTHON@ @gabbletestsdir@/twisted/$i
+    e=$?
+    case "$e" in
+        (0)
+            echo "PASS: $i"
+            ;;
+        (77)
+            echo "SKIP: $i"
+            ;;
+        (*)
+            any_failed=1
+            echo "FAIL: $i ($e)"
+            ;;
+    esac
 done
 
+exit $any_failed
